var programlar = [
    ["Psikoloji (İngilizce) (Burslu)"],
    ["Bilgisayar Mühendisliği (İngilizce) (Ücretli)"],
    ["Bilgisayar Mühendisliği (İngilizce) (Burslu)"],
    ["Film Tasarımı ve Yönetimi (İngilizce) (Burslu)"],
    ["Film Tasarımı ve Yönetimi (İngilizce) (%50 İndirimli)"],
    ["Yeni Medya ve İletişim (İngilizce) (Ücretli)"],
    ["Yeni Medya ve İletişim (İngilizce) (Burslu)"],
    ["Yeni Medya ve İletişim (İngilizce) (%50 İndirimli)"],
    ["Yazılım Mühendisliği (İngilizce) (Ücretli)"],
    ["Yazılım Mühendisliği (İngilizce) (Burslu)"],
    ["Elektrik-Elektronik Mühendisliği (İngilizce) (Burslu)"],
    ["Endüstri Mühendisliği (İngilizce) (Ücretli)"],
    ["Endüstri Mühendisliği (İngilizce) (Burslu)"],
    ["Endüstri Mühendisliği (İngilizce) (%50 İndirimli)"],
    ["İç Mimarlık ve Çevre Tasarımı (İngilizce) (Ücretli)"],
    ["İç Mimarlık ve Çevre Tasarımı (İngilizce) (Burslu)"],
    ["Yönetim Bilişim Sistemleri (İngilizce) (Ücretli)"],
    ["Yönetim Bilişim Sistemleri (İngilizce) (Burslu)"],
    ["Yönetim Bilişim Sistemleri (İngilizce) (%50 İndirimli)"],
    ["İngilizce Mütercim ve Tercümanlık (Ücretli)"],
    ["İngilizce Mütercim ve Tercümanlık (Burslu)"],
    ["İngilizce Mütercim ve Tercümanlık (%50 İndirimli)"],
    ["İç Mimarlık ve Çevre Tasarımı (İngilizce) (%25 İndirimli)"],
    ["Hukuk Fakültesi (Burslu)"],
    ["Psikoloji (İngilizce) (%25 İndirimli)"],
    ["Siyaset Bilimi ve Kamu Yönetimi (İngilizce) (Ücretli)"],
    ["Siyaset Bilimi ve Kamu Yönetimi (İngilizce) (Burslu)"],
    ["Siyaset Bilimi ve Kamu Yönetimi (İngilizce) (%50 İndirimli)"],
    ["Bilgisayar Mühendisliği (İngilizce) (%25 İndirimli)"],
    ["İşletme (İngilizce) (Ücretli)"],
    ["İşletme (İngilizce) (Burslu)"],
    ["İşletme (İngilizce) (%25 İndirimli)"],
    ["Çağdaş Türk Lehçeleri ve Edebiyatları"],
    ["Felsefe"],
    ["Rus Dili ve Edebiyatı"],
    ["Sanat Tarihi"],
    ["Tarih"],
    ["Türk Dili ve Edebiyatı"],
    ["Türk Halkbilimi"],
    ["Hukuk Fakültesi"],
    ["Çalışma Ekonomisi ve Endüstri İlişkileri"],
    ["Ekonometri"],
    ["İktisat"],
    ["İşletme"],
    ["Maliye"],
    ["Uluslararası İlişkiler"],
    ["Gazetecilik"],
    ["Halkla İlişkiler ve Tanıtım"],
    ["Radyo"],
    ["Gastronomi ve Mutfak Sanatları"],
    ["Rekreasyon Yönetimi"],
    ["Turizm İşletmeciliği"],
    ["Biyoloji"],
    ["Kimya"],
    ["Matematik"],
    ["Tarih"],
    ["Türk Dili ve Edebiyatı"],
    ["Sosyoloji"],
    ["Arkeoloji"],
    ["Fransız Dili ve Edebiyatı"],
    ["Tapu Kadastro"],
    ["Seyahat İşletmeciliği ve Turizm Rehberliği"],
    ["Fotoğraf ve Video"],
    ["Kültür Varlıklarını Koruma ve Onarım"],
    ["Gastronomi ve Mutfak Sanatları (M.T.O.K.)"],
    ["Rekreasyon Yönetimi (M.T.O.K.)"],
    ["Sigortacılık"],
    ["Görsel İletişim Tasarımı"],
    ["Siyaset Bilimi ve Kamu Yönetimi"],
    ["Sağlık Yönetimi"],
    ["Uluslararası İlişkiler (İngilizce)"],
    ["İşletme (İngilizce)"],
    ["Sağlık Yönetimi (KKTC Uyruklu)"],
    ["Gazetecilik (KKTC Uyruklu)"],
    ["El Sanatları (M.T.O.K.)"],
    ["Geleneksel Türk Sanatları (M.T.O.K.)"],
    ["Grafik Tasarımı (M.T.O.K.)"],
    ["Görsel Sanatlar (M.T.O.K.)"],
    ["Moda Tasarımı (M.T.O.K.)"],
    ["Tekstil Tasarımı (M.T.O.K.)"],
    ["El Sanatları"],
    ["Kuyumculuk ve Mücevher Tasarımı"],
    ["Moda Tasarımı"],
    ["Tekstil Tasarımı"],
    ["Psikoloji"],
    ["Finans ve Bankacılık"],
    ["Uluslararası Ticaret ve Finansman"],
    ["Fizik"],
    ["İslami İlimler"],
    ["Arapça Mütercim ve Tercümanlık"],
    ["İngiliz Dili ve Edebiyatı (İngilizce)"],
    ["İslami İlimler (M.T.O.K.)"],
    ["Psikoloji (Burslu)"],
    ["Psikoloji (%50 İndirimli)"],
    ["Beslenme ve Diyetetik (Burslu)"],
    ["Hemşirelik (Burslu)"],
    ["Diş Hekimliği Fakültesi (İngilizce) (Ücretli)"],
    ["Diş Hekimliği Fakültesi (İngilizce) (Burslu)"],
    ["Diş Hekimliği Fakültesi (İngilizce) (%50 İndirimli)"],
    ["Diş Hekimliği Fakültesi (Ücretli)"],
    ["Diş Hekimliği Fakültesi (Burslu)"],
    ["Diş Hekimliği Fakültesi (%50 İndirimli)"],
    ["Tıp Fakültesi (İngilizce) (Ücretli)"],
    ["Tıp Fakültesi (İngilizce) (Burslu)"],
    ["Tıp Fakültesi (İngilizce) (%50 İndirimli)"],
    ["Tıp Fakültesi (Ücretli)"],
    ["Tıp Fakültesi (Burslu)"],
    ["Tıp Fakültesi (%50 İndirimli)"],
    ["Eczacılık Fakültesi (Ücretli)"],
    ["Eczacılık Fakültesi (Burslu)"],
    ["Eczacılık Fakültesi (%50 İndirimli)"],
    ["Hukuk Fakültesi (Ücretli)"],
    ["Hukuk Fakültesi (Burslu)"],
    ["Hukuk Fakültesi (%50 İndirimli)"],
    ["Uluslararası Ticaret ve Finansman (İngilizce) (Burslu)"],
    ["Uluslararası Ticaret ve Finansman (İngilizce) (%50 İndirimli)"],
    ["Uluslararası Ticaret ve Finansman (Burslu)"],
    ["Uluslararası Ticaret ve Finansman (%50 İndirimli)"],
    ["Yönetim Bilişim Sistemleri (Burslu)"],
    ["Yönetim Bilişim Sistemleri (%50 İndirimli)"],
    ["Psikoloji (İngilizce) (Burslu)"],
    ["Psikoloji (İngilizce) (%50 İndirimli)"],
    ["Dil ve Konuşma Terapisi (Burslu)"],
    ["Dil ve Konuşma Terapisi (%50 İndirimli)"],
    ["Ebelik (Burslu)"],
    ["Ebelik (%50 İndirimli)"],
    ["Ergoterapi (Burslu)"],
    ["Ergoterapi (%50 İndirimli)"],
    ["Fizyoterapi ve Rehabilitasyon (Burslu)"],
    ["Gastronomi ve Mutfak Sanatları (İngilizce) (Burslu)"],
    ["Gastronomi ve Mutfak Sanatları (İngilizce) (%50 İndirimli)"],
    ["İç Mimarlık ve Çevre Tasarımı (Burslu)"],
    ["İç Mimarlık ve Çevre Tasarımı (%50 İndirimli)"],
    ["Halkla İlişkiler ve Reklamcılık (Burslu)"],
    ["Halkla İlişkiler ve Reklamcılık (%50 İndirimli)"],
    ["Siyaset Bilimi ve Uluslararası İlişkiler (İngilizce) (Burslu)"],
    ["Eczacılık Fakültesi (İngilizce) (Ücretli)"],
    ["Eczacılık Fakültesi (İngilizce) (Burslu)"],
    ["Eczacılık Fakültesi (İngilizce) (%50 İndirimli)"],
    ["Bilgisayar Mühendisliği (İngilizce) (Burslu)"],
    ["Bilgisayar Mühendisliği (İngilizce) (%50 İndirimli)"],
    ["Beslenme ve Diyetetik (%50 İndirimli)"],
    ["Hemşirelik (%50 İndirimli)"],
    ["Hemşirelik (İngilizce) (Burslu)"],
    ["Hemşirelik (İngilizce) (%50 İndirimli)"],
    ["Odyoloji (Burslu)"],
    ["Odyoloji (%50 İndirimli)"],
    ["İngiliz Dili ve Edebiyatı (İngilizce)"],
    ["Uluslararası İlişkiler (İngilizce)"],
    ["Ekonomi (İngilizce)"],
    ["İşletme (İngilizce)"],
    ["Hukuk Fakültesi"],
    ["Ekonomi (İngilizce) (KKTC Uyruklu)"],
    ["Siyaset Bilimi ve Kamu Yönetimi (İngilizce)"],
    ["Sosyoloji (İngilizce)"],
    ["Türk Dili ve Edebiyatı"],
    ["Tarih (İngilizce)"],
    ["Psikoloji (İngilizce)"],
    ["İslami İlimler"],
    ["İngilizce Öğretmenliği (Ücretli)"],
    ["İngilizce Öğretmenliği (%50 İndirimli)"],
    ["İngilizce Öğretmenliği (Burslu)"],
    ["Özel Eğitim Öğretmenliği (Ücretli)"],
    ["Özel Eğitim Öğretmenliği (Burslu)"],
    ["Özel Eğitim Öğretmenliği (%50 İndirimli)"],
    ["Rehberlik ve Psikolojik Danışmanlık (Ücretli)"],
    ["Rehberlik ve Psikolojik Danışmanlık (Burslu)"],
    ["Rehberlik ve Psikolojik Danışmanlık (%50 İndirimli)"],
    ["Psikoloji (Ücretli)"],
    ["Psikoloji (Burslu)"],
    ["Psikoloji (%50 İndirimli)"],
    ["Hukuk Fakültesi (Ücretli)"],
    ["Hukuk Fakültesi (Burslu)"],
    ["Hukuk Fakültesi (%50 İndirimli)"],
    ["İslami İlimler (M.T.O.K.)"],
    ["Japonca Mütercim ve Tercümanlık"],
    ["İlahiyat (Burslu)"],
    ["Alman Dili ve Edebiyatı (Almanca)"],
    ["Amerikan Kültürü ve Edebiyatı (İngilizce)"],
    ["Antropoloji"],
    ["Arap Dili ve Edebiyatı"],
    ["Arkeoloji (İngilizce)"],
    ["Bilgi ve Belge Yönetimi"],
    ["Coğrafya"],
    ["Çağdaş Türk Lehçeleri ve Edebiyatları"],
    ["Çağdaş Yunan Dili ve Edebiyatı"],
    ["Fars Dili ve Edebiyatı"],
    ["Felsefe"],
    ["Fransız Dili ve Edebiyatı"],
    ["Hindoloji"],
    ["Hititoloji"],
    ["Hungaroloji"],
    ["İngiliz Dili ve Edebiyatı (İngilizce)"],
    ["İspanyol Dili ve Edebiyatı (İspanyolca)"],
    ["İtalyan Dili ve Edebiyatı (İtalyanca)"],
    ["Japon Dili ve Edebiyatı"],
    ["Kore Dili ve Edebiyatı"],
    ["Latin Dili ve Edebiyatı"],
    ["Psikoloji"],
    ["Rus Dili ve Edebiyatı (Rusça)"],
    ["Sanat Tarihi"],
    ["Sinoloji"],
    ["Sosyoloji"],
    ["Sümeroloji"],
    ["Tarih"],
    ["Türk Dili ve Edebiyatı"],
    ["Urdu Dili ve Edebiyatı"],
    ["Yunan Dili ve Edebiyatı"],
    ["Diş Hekimliği Fakültesi"],
    ["Eczacılık Fakültesi"],
    ["Bilgisayar ve Öğretim Teknolojileri Öğretmenliği"],
    ["Okul Öncesi Öğretmenliği"],
    ["Rehberlik ve Psikolojik Danışmanlık"],
    ["Sınıf Öğretmenliği"],
    ["Sosyal Bilgiler Öğretmenliği"],
    ["Astronomi ve Uzay Bilimleri"],
    ["Biyoloji"],
    ["Fizik"],
    ["İstatistik"],
    ["Kimya"],
    ["Matematik"],
    ["Hukuk Fakültesi"],
    ["İlahiyat"],
    ["Gazetecilik"],
    ["Halkla İlişkiler ve Tanıtım"],
    ["Radyo"],
    ["Bilgisayar Mühendisliği"],
    ["Jeofizik Mühendisliği"],
    ["Beslenme ve Diyetetik"],
    ["Ebelik"],
    ["Hemşirelik"],
    ["Sosyal Hizmet"],
    ["Çalışma Ekonomisi ve Endüstri İlişkileri"],
    ["İktisat"],
    ["İşletme"],
    ["Maliye"],
    ["Siyaset Bilimi ve Kamu Yönetimi"],
    ["Uluslararası İlişkiler"],
    ["Tıp Fakültesi"],
    ["Veteriner Fakültesi"],
    ["Peyzaj Mimarlığı"],
    ["Klasik Arkeoloji"],
    ["Protohistorya ve Ön Asya Arkeolojisi"],
    ["Bahçe Bitkileri"],
    ["Bitki Koruma"],
    ["Tarım Ekonomisi"],
    ["Tarımsal Yapılar ve Sulama"],
    ["Tarla Bitkileri"],
    ["Toprak Bilimi ve Bitki Besleme"],
    ["Zootekni"],
    ["Süt Teknolojisi"],
    ["Su Ürünleri Mühendisliği"],
    ["Bilgisayar Mühendisliği (İngilizce)"],
    ["Çocuk Gelişimi"],
    ["İlahiyat (İngilizce)"],
    ["Tarih Öncesi Arkeolojisi"],
    ["Elektrik-Elektronik Mühendisliği (İngilizce)"],
    ["Tarım Makineleri ve Teknolojileri Mühendisliği"],
    ["Biyomedikal Mühendisliği (İngilizce)"],
    ["Biyoloji (İngilizce)"],
    ["Kimya (İngilizce)"],
    ["Eczacılık Fakültesi (İngilizce)"],
    ["Veteriner Fakültesi (İngilizce)"],
    ["Sağlık Yönetimi"],
    ["Matematik (İngilizce)"],
    ["Kültür Varlıklarını Koruma ve Onarım"],
    ["Gayrimenkul Geliştirme ve Yönetimi"],
    ["Özel Eğitim Öğretmenliği"],
    ["Su Ürünleri Mühendisliği (İngilizce)"],
    ["Enerji Mühendisliği (İngilizce)"],
    ["Felsefe (İngilizce)"],
    ["Çağdaş Yunan Dili ve Edebiyatı (KKTC Uyruklu)"],
    ["İtalyan Dili ve Edebiyatı (İtalyanca) (KKTC Uyruklu)"],
    ["Tıp Fakültesi (İngilizce)"],
    ["Fizik Mühendisliği (İngilizce)"],
    ["Kimya Mühendisliği (İngilizce)"],
    ["Gıda Mühendisliği (İngilizce)"],
    ["Ermeni Dili ve Kültürü (Ermenice)"],
    ["Bulgar Dili ve Edebiyatı (Bulgarca)"],
    ["Politika ve Ekonomi (İngilizce)"],
    ["Aktüerya Bilimleri"],
    ["Diş Hekimliği Fakültesi (İngilizce)"],
    ["İşletme (İngilizce)"],
    ["Coğrafya (İngilizce)"],
    ["Jeoloji Mühendisliği (İngilizce)"],
    ["Jeofizik Mühendisliği (İngilizce)"],
    ["Halkbilimi"],
    ["Dilbilimi"],
    ["Leh Dili ve Edebiyatı (Lehçe)"],
    ["Ortez ve Protez"],
    ["Arap Dili ve Edebiyatı (Uzaktan Öğretim)"],
    ["Coğrafya (Uzaktan Öğretim)"],
    ["İngiliz Dili ve Edebiyatı (İngilizce) (Uzaktan Öğretim)"],
    ["Rus Dili ve Edebiyatı (Rusça) (Uzaktan Öğretim)"],
    ["Sanat Tarihi (Uzaktan Öğretim)"],
    ["Sinoloji (Uzaktan Öğretim)"],
    ["Gazetecilik (Uzaktan Öğretim)"],
    ["Halkla İlişkiler ve Tanıtım (Uzaktan Öğretim)"],
    ["Radyo"],
    ["Sosyal Hizmet (Uzaktan Öğretim)"],
    ["Sanat Tarihi (KKTC Uyruklu)"],
    ["Veteriner Fakültesi (İngilizce) (KKTC Uyruklu)"],
    ["İlahiyat (M.T.O.K.)"],
    ["Elektronik Ticaret ve Yönetimi (Açıköğretim)"],
    ["Yönetim Bilişim Sistemleri (Açıköğretim)"],
    ["Tıp Fakültesi (İngilizce)"],
    ["Hukuk Fakültesi"],
    ["Bilgisayar Mühendisliği (İngilizce)"],
    ["Makine Mühendisliği (İngilizce)"],
    ["İktisat (İngilizce)"],
    ["Uluslararası İlişkiler (İngilizce)"],
    ["Maliye (İngilizce)"],
    ["Siyaset Bilimi ve Kamu Yönetimi (İngilizce)"],
    ["Hemşirelik"],
    ["Felsefe"],
    ["Sosyoloji"],
    ["Tarih"],
    ["Türk Dili ve Edebiyatı"],
    ["Tıp Fakültesi"],
    ["İşletme (İngilizce)"],
    ["Uluslararası Ticaret ve İşletmecilik (İngilizce)"],
    ["Yönetim Bilişim Sistemleri (İngilizce)"],
    ["Bilgi ve Belge Yönetimi"],
    ["İslami İlimler"],
    ["Psikoloji (İngilizce)"],
    ["Elektrik-Elektronik Mühendisliği (İngilizce)"],
    ["Tıp Fakültesi (KKTC Uyruklu)"],
    ["Diş Hekimliği Fakültesi"],
    ["Fizyoterapi ve Rehabilitasyon"],
    ["Sosyal Hizmet"],
    ["İnşaat Mühendisliği (İngilizce)"],
    ["Odyoloji"],
    ["Beslenme ve Diyetetik"],
    ["Metalurji ve Malzeme Mühendisliği (İngilizce)"],
    ["Endüstri Mühendisliği (İngilizce)"],
    ["Mimarlık (İngilizce)"],
    ["Enerji Sistemleri Mühendisliği (İngilizce)"],
    ["Matematik (İngilizce)"],
    ["Sağlık Yönetimi"],
    ["Çocuk Gelişimi"],
    ["Dil ve Konuşma Terapisi"],
    ["Görsel İletişim Tasarımı"],
    ["Havacılık ve Uzay Mühendisliği (İngilizce)"],
    ["Finans ve Bankacılık (İngilizce)"],
    ["Finans ve Bankacılık"],
    ["Arapça Mütercim ve Tercümanlık"],
    ["İngilizce Mütercim ve Tercümanlık"],
    ["Uluslararası Ticaret ve Lojistik"],
    ["Çocuk Gelişimi (KKTC Uyruklu)"],
    ["İslami İlimler (M.T.O.K.)"],
    ["Yazılım Mühendisliği (İngilizce)"],
    ["Spor Yöneticiliği"],
    ["İngiliz Dili ve Edebiyatı (İngilizce) (Burslu)"],
    ["İngiliz Dili ve Edebiyatı (İngilizce) (%50 İndirimli)"],
    ["Matematik (İngilizce) (Burslu)"],
    ["Psikoloji (İngilizce) (Ücretli)"],
    ["Psikoloji (İngilizce) (Burslu)"],
    ["Halkla İlişkiler ve Reklamcılık (İngilizce) (Burslu)"],
    ["Halkla İlişkiler ve Reklamcılık (İngilizce) (%50 İndirimli)"],
    ["İktisat (İngilizce) (Burslu)"],
    ["İktisat (İngilizce) (%50 İndirimli)"],
    ["İşletme (İngilizce) (Burslu)"],
    ["İşletme (İngilizce) (%50 İndirimli)"],
    ["İşletme (Burslu)"],
    ["Uluslararası İlişkiler (İngilizce) (Burslu)"],
    ["Uluslararası İlişkiler (İngilizce) (%50 İndirimli)"],
    ["Bilgisayar Mühendisliği (İngilizce) (Burslu)"],
    ["Bilişim Sistemleri Mühendisliği (İngilizce) (Burslu)"],
    ["Bilişim Sistemleri Mühendisliği (İngilizce) (%50 İndirimli)"],
    ["Elektrik-Elektronik Mühendisliği (İngilizce) (Burslu)"],
    ["Endüstri Mühendisliği (İngilizce) (Burslu)"],
    ["Endüstri Mühendisliği (İngilizce) (%50 İndirimli)"],
    ["İnşaat Mühendisliği (İngilizce) (Burslu)"],
    ["İnşaat Mühendisliği (İngilizce) (%50 İndirimli)"],
    ["Metalurji ve Malzeme Mühendisliği (İngilizce) (Burslu)"],
    ["Metalurji ve Malzeme Mühendisliği (İngilizce) (%50 İndirimli)"],
    ["Mekatronik Mühendisliği (İngilizce) (Burslu)"],
    ["Mekatronik Mühendisliği (İngilizce) (%50 İndirimli)"],
    ["Yazılım Mühendisliği (İngilizce) (Burslu)"],
    ["Hukuk Fakültesi (Ücretli)"],
    ["Hukuk Fakültesi (Burslu)"],
    ["Enerji Sistemleri Mühendisliği (İngilizce) (Burslu)"],
    ["Makine Mühendisliği (İngilizce) (Burslu)"],
    ["Otomotiv Mühendisliği (İngilizce) (Burslu)"],
    ["Siyaset Bilimi ve Kamu Yönetimi (Burslu)"],
    ["Mimarlık (Burslu)"],
    ["İktisat (Burslu)"],
    ["Uluslararası Ticaret ve Lojistik (İngilizce) (Burslu)"],
    ["Uluslararası Ticaret ve Lojistik (İngilizce) (%50 İndirimli)"],
    ["Siyaset Bilimi ve Kamu Yönetimi (%50 İndirimli)"],
    ["Makine Mühendisliği (İngilizce) (%50 İndirimli)"],
    ["Otomotiv Mühendisliği (İngilizce) (%50 İndirimli)"],
    ["Bilgisayar Mühendisliği (İngilizce) (%25 İndirimli)"],
    ["Elektrik-Elektronik Mühendisliği (İngilizce) (%25 İndirimli)"],
    ["Yazılım Mühendisliği (İngilizce) (%25 İndirimli)"],
    ["İç Mimarlık ve Çevre Tasarımı (Burslu)"],
    ["Maliye (Burslu)"],
    ["Maliye (%50 İndirimli)"],
    ["İç Mimarlık ve Çevre Tasarımı (Ücretli)"],
    ["Pilotaj (İngilizce) (Ücretli)"],
    ["Pilotaj (İngilizce) (Burslu)"],
    ["İç Mimarlık ve Çevre Tasarımı (%25 İndirimli)"],
    ["Havacılık Yönetimi (İngilizce) (Burslu)"],
    ["Havacılık Yönetimi (İngilizce) (%50 İndirimli)"],
    ["Grafik Tasarımı (Burslu)"],
    ["Grafik Tasarımı (%50 İndirimli)"],
    ["Beslenme ve Diyetetik (İngilizce) (Burslu)"],
    ["Beslenme ve Diyetetik (İngilizce) (%25 İndirimli)"],
    ["Fizyoterapi ve Rehabilitasyon (İngilizce) (Burslu)"],
    ["Fizyoterapi ve Rehabilitasyon (İngilizce) (%25 İndirimli)"],
    ["Hemşirelik (İngilizce) (Burslu)"],
    ["Hemşirelik (İngilizce) (%25 İndirimli)"],
    ["Tıp Fakültesi (İngilizce) (Ücretli)"],
    ["Tıp Fakültesi (İngilizce) (Burslu)"],
    ["Tıp Fakültesi (İngilizce) (%25 İndirimli)"],
    ["Uçak Elektrik ve Elektroniği (İngilizce) (Burslu)"],
    ["Uçak Elektrik ve Elektroniği (İngilizce) (%25 İndirimli)"],
    ["Uçak Gövde ve Motor Bakımı (İngilizce) (Burslu)"],
    ["Uçak Gövde ve Motor Bakımı (İngilizce) (%25 İndirimli)"],
    ["Endüstriyel Tasarım (Burslu)"],
    ["Endüstriyel Tasarım (%50 İndirimli)"],
    ["İngilizce Mütercim ve Tercümanlık (Burslu)"],
    ["İngilizce Mütercim ve Tercümanlık (%25 İndirimli)"],
    ["Tekstil ve Moda Tasarımı (Burslu)"],
    ["Turizm İşletmeciliği (İngilizce) (Burslu)"],
    ["Matematik (İngilizce) (%50 İndirimli)"],
    ["Psikoloji (İngilizce) (%25 İndirimli)"],
    ["Tekstil ve Moda Tasarımı (%50 İndirimli)"],
    ["Hukuk Fakültesi (%25 İndirimli)"],
    ["İktisat (%50 İndirimli)"],
    ["İşletme (%50 İndirimli)"],
    ["Turizm İşletmeciliği (İngilizce) (%50 İndirimli)"],
    ["Enerji Sistemleri Mühendisliği (İngilizce) (%50 İndirimli)"],
    ["Kimya Mühendisliği (İngilizce) (Burslu)"],
    ["Kimya Mühendisliği (İngilizce) (%50 İndirimli)"],
    ["Havacılık ve Uzay Mühendisliği (İngilizce) (Burslu)"],
    ["Havacılık ve Uzay Mühendisliği (İngilizce) (%50 İndirimli)"],
    ["Mimarlık (%50 İndirimli)"],
    ["Çocuk Gelişimi (Burslu)"],
    ["Çocuk Gelişimi (%50 İndirimli)"],
    ["Odyoloji (İngilizce) (Burslu)"],
    ["Odyoloji (İngilizce) (%50 İndirimli)"],
    ["Diş Hekimliği Fakültesi (Ücretli)"],
    ["İlköğretim Matematik Öğretmenliği (Ücretli)"],
    ["İlköğretim Matematik Öğretmenliği (%50 İndirimli)"],
    ["İngilizce Öğretmenliği (Ücretli)"],
    ["İngilizce Öğretmenliği (%50 İndirimli)"],
    ["Okul Öncesi Öğretmenliği (Ücretli)"],
    ["Okul Öncesi Öğretmenliği (%50 İndirimli)"],
    ["Sınıf Öğretmenliği (Ücretli)"],
    ["Sınıf Öğretmenliği (%50 İndirimli)"],
    ["Türkçe Öğretmenliği (Ücretli)"],
    ["Türkçe Öğretmenliği (%50 İndirimli)"],
    ["Amerikan Kültürü ve Edebiyatı (Ücretli)"],
    ["Amerikan Kültürü ve Edebiyatı (%50 İndirimli)"],
    ["Türk Dili ve Edebiyatı (Ücretli)"],
    ["Türk Dili ve Edebiyatı (%50 İndirimli)"],
    ["Hukuk Fakültesi (Ücretli)"],
    ["İktisat (Ücretli)"],
    ["İktisat (%50 İndirimli)"],
    ["İşletme (Ücretli)"],
    ["İşletme (%50 İndirimli)"],
    ["Siyaset Bilimi ve Uluslararası İlişkiler (Ücretli)"],
    ["Siyaset Bilimi ve Uluslararası İlişkiler (%50 İndirimli)"],
    ["Bilgisayar Mühendisliği (Ücretli)"],
    ["Biyomedikal Mühendisliği (%50 İndirimli)"],
    ["Elektrik-Elektronik Mühendisliği (Ücretli)"],
    ["Endüstri Mühendisliği (Ücretli)"],
    ["Endüstri Mühendisliği (%50 İndirimli)"],
    ["Makine Mühendisliği (Ücretli)"],
    ["Makine Mühendisliği (%50 İndirimli)"],
    ["Beslenme ve Diyetetik (Ücretli)"],
    ["Hemşirelik (Burslu)"],
    ["Sosyal Hizmet (Ücretli)"],
    ["Sosyal Hizmet (%50 İndirimli)"],
    ["Hemşirelik (Ücretli)"],
    ["Tıp Fakültesi (Ücretli)"],
    ["Tıp Fakültesi (%50 İndirimli)"],
    ["Muhasebe ve Finans Yönetimi (%50 İndirimli)"],
    ["Yönetim Bilişim Sistemleri (Ücretli)"],
    ["Yönetim Bilişim Sistemleri (%50 İndirimli)"],
    ["Rehberlik ve Psikolojik Danışmanlık (Ücretli)"],
    ["Diş Hekimliği Fakültesi (%25 İndirimli)"],
    ["Bilgisayar Mühendisliği (%25 İndirimli)"],
    ["Elektrik-Elektronik Mühendisliği (%25 İndirimli)"],
    ["Beslenme ve Diyetetik (%25 İndirimli)"],
    ["Rehberlik ve Psikolojik Danışmanlık (%50 İndirimli)"],
    ["Diş Hekimliği Fakültesi (Burslu)"],
    ["İlköğretim Matematik Öğretmenliği (Burslu)"],
    ["İngilizce Öğretmenliği (Burslu)"],
    ["Okul Öncesi Öğretmenliği (Burslu)"],
    ["Rehberlik ve Psikolojik Danışmanlık (Burslu)"],
    ["Sınıf Öğretmenliği (Burslu)"],
    ["Türkçe Öğretmenliği (Burslu)"],
    ["Amerikan Kültürü ve Edebiyatı (Burslu)"],
    ["Türk Dili ve Edebiyatı (Burslu)"],
    ["Hukuk Fakültesi (Burslu)"],
    ["İktisat (Burslu)"],
    ["İşletme (Burslu)"],
    ["Siyaset Bilimi ve Uluslararası İlişkiler (Burslu)"],
    ["Bilgisayar Mühendisliği (Burslu)"],
    ["Biyomedikal Mühendisliği (Burslu)"],
    ["Elektrik-Elektronik Mühendisliği (Burslu)"],
    ["Endüstri Mühendisliği (Burslu)"],
    ["Makine Mühendisliği (Burslu)"],
    ["Beslenme ve Diyetetik (Burslu)"],
    ["Sosyal Hizmet (Burslu)"],
    ["Tıp Fakültesi (Burslu)"],
    ["Muhasebe ve Finans Yönetimi (Burslu)"],
    ["Yönetim Bilişim Sistemleri (Burslu)"],
    ["Hemşirelik (%50 İndirimli)"],
    ["Psikoloji (Ücretli)"],
    ["Psikoloji (Burslu)"],
    ["Psikoloji (%25 İndirimli)"],
    ["Teknoloji ve Bilgi Yönetimi (Ücretli)"],
    ["Teknoloji ve Bilgi Yönetimi (Burslu)"],
    ["Teknoloji ve Bilgi Yönetimi (%50 İndirimli)"],
    ["Mimarlık (Ücretli)"],
    ["Mimarlık (Burslu)"],
    ["Mimarlık (%25 İndirimli)"],
    ["Sosyoloji (Burslu)"],
    ["Sosyoloji (%50 İndirimli)"],
    ["İç Mimarlık ve Çevre Tasarımı (Ücretli)"],
    ["İç Mimarlık ve Çevre Tasarımı (Burslu)"],
    ["İç Mimarlık ve Çevre Tasarımı (%25 İndirimli)"],
    ["Sağlık Yönetimi (Burslu)"],
    ["Sağlık Yönetimi (%50 İndirimli)"],
    ["İşletme (İngilizce) (Ücretli)"],
    ["İşletme (İngilizce) (Burslu)"],
    ["İşletme (İngilizce) (%50 İndirimli)"],
    ["Odyoloji (Ücretli)"],
    ["Odyoloji (Burslu)"],
    ["Odyoloji (%50 İndirimli)"],
    ["Çizgi Film ve Animasyon (Ücretli)"],
    ["Çizgi Film ve Animasyon (Burslu)"],
    ["Çizgi Film ve Animasyon (%50 İndirimli)"],
    ["Siyaset Bilimi ve Uluslararası İlişkiler (İngilizce) (Ücretli)"],
    ["Siyaset Bilimi ve Uluslararası İlişkiler (İngilizce) (Burslu)"],
    ["Siyaset Bilimi ve Uluslararası İlişkiler (İngilizce) (%50 İndirimli)"],
    ["Moleküler Biyoloji ve Genetik (Ücretli)"],
    ["Moleküler Biyoloji ve Genetik (Burslu)"],
    ["Moleküler Biyoloji ve Genetik (%50 İndirimli)"],
    ["Gastronomi ve Mutfak Sanatları (Ücretli)"],
    ["Gastronomi ve Mutfak Sanatları (Burslu)"],
    ["Gastronomi ve Mutfak Sanatları (%25 İndirimli)"],
    ["İktisat (İngilizce) (Ücretli)"],
    ["İktisat (İngilizce) (Burslu)"],
    ["Sosyoloji (İngilizce) (Burslu)"],
    ["Sosyoloji (İngilizce) (%50 İndirimli)"],
    ["Turizm ve Otel İşletmeciliği (Burslu)"],
    ["Biyomedikal Cihaz Teknolojisi (Ücretli)"],
    ["Biyomedikal Cihaz Teknolojisi (Burslu)"],
    ["Radyo ve Televizyon Programcılığı (Burslu)"],
    ["Fotoğrafçılık ve Kameramanlık (Burslu)"],
    ["Turizm ve Seyahat Hizmetleri (Burslu)"],
    ["Muhasebe ve Vergi Uygulamaları (Burslu)"],
    ["Büro Yönetimi ve Yönetici Asistanlığı (Burslu)"],
    ["Büro Yönetimi ve Yönetici Asistanlığı (%50 İndirimli)"],
    ["Fotoğrafçılık ve Kameramanlık (%50 İndirimli)"],
    ["Muhasebe ve Vergi Uygulamaları (%50 İndirimli)"],
    ["Radyo ve Televizyon Programcılığı (%50 İndirimli)"],
    ["Turizm ve Otel İşletmeciliği (%50 İndirimli)"],
    ["Turizm ve Seyahat Hizmetleri (%50 İndirimli)"],
    ["Biyomedikal Cihaz Teknolojisi (%50 İndirimli)"],
    ["Bilgisayar Programcılığı (Ücretli)"],
    ["Bilgisayar Programcılığı (Burslu)"],
    ["Bilgisayar Programcılığı (%25 İndirimli)"],
    ["Aşçılık (Burslu)"],
    ["Aşçılık (%25 İndirimli)"],
    ["Sağlık Bilgi Sistemleri Teknikerliği (Burslu)"],
    ["Çocuk Gelişimi (Ücretli)"],
    ["Çocuk Gelişimi (Burslu)"],
    ["Çocuk Gelişimi (%25 İndirimli)"],
    ["Diş Hekimliği Fakültesi (İngilizce) (Burslu)"],
    ["Diş Hekimliği Fakültesi (İngilizce) (Ücretli)"],
    ["Tıp Fakültesi (İngilizce) (Ücretli)"],
    ["Tıp Fakültesi (İngilizce) (Burslu)"],
    ["Tıp Fakültesi (İngilizce) (%50 İndirimli)"],
    ["Moleküler Biyoloji ve Genetik (İngilizce) (Burslu)"],
    ["Moleküler Biyoloji ve Genetik (İngilizce) (Ücretli)"],
    ["Moleküler Biyoloji ve Genetik (İngilizce) (%50 İndirimli)"],
    ["Bilgisayar Programcılığı (İÖ) (Ücretli)"],
    ["Bilgisayar Programcılığı (İÖ) (%25 İndirimli)"],
    ["Bilgisayar Programcılığı (İÖ) (Burslu)"],
    ["Görsel İletişim Tasarımı (Burslu)"],
    ["Görsel İletişim Tasarımı (Ücretli)"],
    ["Görsel İletişim Tasarımı (%25 İndirimli)"],
    ["İktisat (İngilizce) (%50 İndirimli)"],
    ["Sağlık Bilgi Sistemleri Teknikerliği (%50 İndirimli)"],
    ["İnşaat Mühendisliği (İngilizce) (Burslu)"],
    ["Diş Hekimliği Fakültesi (İngilizce) (%25 İndirimli)"],
    ["Makine Mühendisliği (İngilizce) (Burslu)"],
    ["Elektrik-Elektronik Mühendisliği (İngilizce) (Burslu)"],
    ["Film Tasarımı ve Yönetimi (Ücretli)"],
    ["Film Tasarımı ve Yönetimi (Burslu)"],
    ["Film Tasarımı ve Yönetimi (%25 İndirimli)"],
    ["İngilizce Mütercim ve Tercümanlık (Ücretli)"],
    ["İngilizce Mütercim ve Tercümanlık (Burslu)"],
    ["İngilizce Mütercim ve Tercümanlık (%50 İndirimli)"],
    ["Tekstil ve Moda Tasarımı (Burslu)"],
    ["Tekstil ve Moda Tasarımı (%50 İndirimli)"],
    ["İletişim ve Tasarımı (Ücretli)"],
    ["İletişim ve Tasarımı (Burslu)"],
    ["İletişim ve Tasarımı (%50 İndirimli)"],
    ["Eczacılık Fakültesi (Ücretli)"],
    ["Eczacılık Fakültesi (Burslu)"],
    ["Eczacılık Fakültesi (%25 İndirimli)"],
    ["Uluslararası Ticaret ve Finansman (Ücretli)"],
    ["Uluslararası Ticaret ve Finansman (Burslu)"],
    ["Uluslararası Ticaret ve Finansman (%50 İndirimli)"],
    ["Sigortacılık (Burslu)"],
    ["Sigortacılık (%50 İndirimli)"],
    ["Turizm İşletmeciliği (Burslu)"],
    ["Turizm İşletmeciliği (%50 İndirimli)"],
    ["Hukuk Fakültesi (%50 İndirimli)"],
    ["Halkla İlişkiler ve Tanıtım (Ücretli)"],
    ["Halkla İlişkiler ve Tanıtım (Burslu)"],
    ["Halkla İlişkiler ve Tanıtım (%50 İndirimli)"],
    ["Radyo"],
    ["Radyo"],
    ["Radyo"],
    ["Fizyoterapi ve Rehabilitasyon (Ücretli)"],
    ["Fizyoterapi ve Rehabilitasyon (Burslu)"],
    ["Fizyoterapi ve Rehabilitasyon (%25 İndirimli)"],
    ["Uluslararası Finans ve Bankacılık  (Burslu)"],
    ["Uluslararası Finans ve Bankacılık  (%50 İndirimli)"],
    ["İngiliz Dili ve Edebiyatı (İngilizce) (Burslu)"],
    ["Hukuk Fakültesi (Ücretli)"],
    ["Hukuk Fakültesi (Burslu)"],
    ["İktisat (İngilizce) (Burslu)"],
    ["İşletme (İngilizce) (Burslu)"],
    ["Siyaset Bilimi ve Uluslararası İlişkiler (İngilizce) (Burslu)"],
    ["Bilgisayar Mühendisliği (İngilizce) (Burslu)"],
    ["Endüstri Mühendisliği (İngilizce) (Burslu)"],
    ["İç Mimarlık (İngilizce) (Burslu)"],
    ["Mimarlık (İngilizce) (Ücretli)"],
    ["Mimarlık (İngilizce) (Burslu)"],
    ["Mimarlık (İngilizce) (%50 İndirimli)"],
    ["Mekatronik Mühendisliği (İngilizce) (Burslu)"],
    ["Mekatronik Mühendisliği (İngilizce) (%50 İndirimli)"],
    ["Makine Mühendisliği (İngilizce) (Burslu)"],
    ["Makine Mühendisliği (İngilizce) (%50 İndirimli)"],
    ["İngiliz Dili ve Edebiyatı (İngilizce) (%50 İndirimli)"],
    ["İktisat (İngilizce) (%50 İndirimli)"],
    ["İşletme (İngilizce) (%50 İndirimli)"],
    ["Siyaset Bilimi ve Uluslararası İlişkiler (İngilizce) (%50 İndirimli)"],
    ["Bilgisayar Mühendisliği (İngilizce) (%50 İndirimli)"],
    ["Endüstri Mühendisliği (İngilizce) (%50 İndirimli)"],
    ["Psikoloji (İngilizce) (Ücretli)"],
    ["Psikoloji (İngilizce) (Burslu)"],
    ["Psikoloji (İngilizce) (%50 İndirimli)"],
    ["İnşaat Mühendisliği (İngilizce) (Burslu)"],
    ["İnşaat Mühendisliği (İngilizce) (%50 İndirimli)"],
    ["Şehir ve Bölge Planlama (İngilizce) (Burslu)"],
    ["Şehir ve Bölge Planlama (İngilizce) (%50 İndirimli)"],
    ["Hukuk Fakültesi (%50 İndirimli)"],
    ["Elektrik-Elektronik Mühendisliği (İngilizce) (Burslu)"],
    ["Elektrik-Elektronik Mühendisliği (İngilizce) (%50 İndirimli)"],
    ["Matematik (İngilizce) (Burslu)"],
    ["Matematik (İngilizce) (%50 İndirimli)"],
    ["İç Mimarlık (İngilizce) (%50 İndirimli)"],
    ["Halkla İlişkiler ve Reklamcılık (Burslu)"],
    ["Halkla İlişkiler ve Reklamcılık (%50 İndirimli)"],
    ["Dış Ticaret (İngilizce) (Burslu)"],
    ["Dış Ticaret (İngilizce) (%50 İndirimli)"],
    ["Adalet (Burslu)"],
    ["Adalet (%50 İndirimli)"],
    ["Yazılım Mühendisliği (İngilizce) (Burslu)"],
    ["Yazılım Mühendisliği (İngilizce) (%50 İndirimli)"],
    ["İngilizce Mütercim ve Tercümanlık (Burslu)"],
    ["İngilizce Mütercim ve Tercümanlık (%50 İndirimli)"],
    ["Uluslararası Ticaret ve Finansman (İngilizce) (Burslu)"],
    ["Uluslararası Ticaret ve Finansman (İngilizce) (%50 İndirimli)"],
    ["Yönetim Bilişim Sistemleri (İngilizce) (Burslu)"],
    ["Yönetim Bilişim Sistemleri (İngilizce) (%50 İndirimli)"],
    ["Bilgisayar Programcılığı (İngilizce) (Burslu)"],
    ["Bilgisayar Programcılığı (İngilizce) (%50 İndirimli)"],
    ["Diş Hekimliği Fakültesi"],
    ["Eczacılık Fakültesi"],
    ["Biyoloji"],
    ["Fizik"],
    ["İstatistik"],
    ["Kimya"],
    ["Matematik"],
    ["Almanca Öğretmenliği"],
    ["Arapça Öğretmenliği"],
    ["Bilgisayar ve Öğretim Teknolojileri Öğretmenliği"],
    ["Biyoloji Öğretmenliği"],
    ["Coğrafya Öğretmenliği"],
    ["Felsefe Grubu Öğretmenliği"],
    ["Fen Bilgisi Öğretmenliği"],
    ["Fizik Öğretmenliği"],
    ["Fransızca Öğretmenliği"],
    ["İlköğretim Matematik Öğretmenliği"],
    ["İngilizce Öğretmenliği"],
    ["Kimya Öğretmenliği"],
    ["Matematik Öğretmenliği"],
    ["Rehberlik ve Psikolojik Danışmanlık"],
    ["Sınıf Öğretmenliği"],
    ["Sosyal Bilgiler Öğretmenliği"],
    ["Tarih Öğretmenliği"],
    ["Türk Dili ve Edebiyatı Öğretmenliği"],
    ["Türkçe Öğretmenliği"],
    ["Bilgisayar Mühendisliği"],
    ["Elektrik-Elektronik Mühendisliği"],
    ["Endüstri Mühendisliği"],
    ["İnşaat Mühendisliği"],
    ["Kimya Mühendisliği"],
    ["Makine Mühendisliği"],
    ["Mimarlık"],
    ["Şehir ve Bölge Planlama"],
    ["Tıp Fakültesi"],
    ["Okul Öncesi Öğretmenliği"],
    ["Hemşirelik"],
    ["Tıp Fakültesi (İngilizce)"],
    ["Beslenme ve Diyetetik"],
    ["Fizyoterapi ve Rehabilitasyon"],
    ["Metalurji ve Malzeme Mühendisliği"],
    ["Metalurji ve Malzeme Mühendisliği (M.T.O.K.)"],
    ["Elektrik-Elektronik Mühendisliği (M.T.O.K.)"],
    ["Elektrik-Elektronik Mühendisliği"],
    ["Otomotiv Mühendisliği (M.T.O.K.)"],
    ["Otomotiv Mühendisliği"],
    ["İmalat Mühendisliği"],
    ["Enerji Sistemleri Mühendisliği"],
    ["Enerji Sistemleri Mühendisliği (M.T.O.K.)"],
    ["İnşaat Mühendisliği"],
    ["İnşaat Mühendisliği (M.T.O.K.)"],
    ["Bilgisayar Mühendisliği"],
    ["Bilgisayar Mühendisliği (M.T.O.K.)"],
    ["Ağaç İşleri Endüstri Mühendisliği"],
    ["Endüstriyel Tasarım Mühendisliği"],
    ["Endüstriyel Tasarım Mühendisliği (M.T.O.K.)"],
    ["Enerji Sistemleri Mühendisliği (KKTC Uyruklu)"],
    ["Tıp Fakültesi (KKTC Uyruklu)"],
    ["Şehir ve Bölge Planlama (KKTC Uyruklu)"],
    ["Kimya Mühendisliği (İngilizce)"],
    ["Elektrik-Elektronik Mühendisliği (İngilizce)"],
    ["İnşaat Mühendisliği (İngilizce)"],
    ["Makine Mühendisliği (İngilizce)"],
    ["Endüstri Mühendisliği (İngilizce)"],
    ["Özel Eğitim Öğretmenliği"],
    ["Rekreasyon"],
    ["Spor Yöneticiliği"],
    ["Tıbbi Dokümantasyon ve Sekreterlik"],
    ["Tıbbi Laboratuvar Teknikleri"],
    ["Tıbbi Görüntüleme Teknikleri"],
    ["İlk ve Acil Yardım"],
    ["Yaşlı Bakımı"],
    ["Patoloji Laboratuvar Teknikleri"],
    ["Ağız ve Diş Sağlığı"],
    ["Bilgisayar Programcılığı"],
    ["Makine"],
    ["Endüstriyel Kalıpçılık"],
    ["Elektronik Teknolojisi"],
    ["Mekatronik"],
    ["Kimya Teknolojisi"],
    ["Kaynak Teknolojisi"],
    ["Endüstri Ürünleri Tasarımı"],
    ["Elektrik Enerjisi Üretim"],
    ["Polimer Teknolojisi"],
    ["Uçak Teknolojisi"],
    ["Sosyal Hizmet"],
    ["Kaynak Teknolojisi (KKTC Uyruklu)"],
    ["Endüstriyel Tasarım"],
    ["Matematik (Uzaktan Öğretim)"],
    ["Endüstri Mühendisliği (İngilizce) (KKTC Uyruklu)"],
    ["İnşaat Mühendisliği (KKTC Uyruklu)"],
    ["Odyoloji"],
    ["Fotonik"],
    ["Bilişim Güvenliği Teknolojisi"],
    ["Kontrol ve Otomasyon Teknolojisi"],
    ["Diş Hekimliği Fakültesi"],
    ["Eczacılık Fakültesi"],
    ["Alman Dili ve Edebiyatı"],
    ["Amerikan Kültürü ve Edebiyatı (İngilizce)"],
    ["Arkeoloji"],
    ["Bilgi ve Belge Yönetimi"],
    ["Felsefe"],
    ["Fransız Dili ve Edebiyatı"],
    ["İngiliz Dilbilimi (İngilizce)"],
    ["İngiliz Dili ve Edebiyatı (İngilizce)"],
    ["Psikoloji"],
    ["Sanat Tarihi"],
    ["Sosyoloji"],
    ["Tarih"],
    ["Türk Dili ve Edebiyatı"],
    ["Türk Halkbilimi"],
    ["Almanca Öğretmenliği (Almanca)"],
    ["Bilgisayar ve Öğretim Teknolojileri Öğretmenliği"],
    ["Biyoloji Öğretmenliği"],
    ["Fen Bilgisi Öğretmenliği"],
    ["Fizik Öğretmenliği"],
    ["Fransızca Öğretmenliği"],
    ["İlköğretim Matematik Öğretmenliği"],
    ["İngilizce Öğretmenliği (İngilizce)"],
    ["Kimya Öğretmenliği"],
    ["Matematik Öğretmenliği"],
    ["Okul Öncesi Öğretmenliği"],
    ["Rehberlik ve Psikolojik Danışmanlık"],
    ["Sınıf Öğretmenliği"],
    ["Aktüerya Bilimleri"],
    ["Biyoloji"],
    ["İstatistik"],
    ["Kimya"],
    ["Matematik"],
    ["İç Mimarlık ve Çevre Tasarımı"],
    ["Aile ve Tüketici Bilimleri"],
    ["İktisat"],
    ["İktisat (İngilizce)"],
    ["İşletme (İngilizce)"],
    ["Maliye"],
    ["Siyaset Bilimi ve Kamu Yönetimi (İngilizce)"],
    ["Uluslararası İlişkiler (İngilizce)"],
    ["Elektrik-Elektronik Mühendisliği (İngilizce)"],
    ["Endüstri Mühendisliği (İngilizce)"],
    ["Fizik Mühendisliği"],
    ["Gıda Mühendisliği"],
    ["Hidrojeoloji Mühendisliği"],
    ["Jeoloji Mühendisliği"],
    ["Kimya Mühendisliği (İngilizce)"],
    ["Maden Mühendisliği (İngilizce)"],
    ["Nükleer Enerji Mühendisliği (İngilizce)"],
    ["Tıp"],
    ["Tıp (İngilizce)"],
    ["Hemşirelik"],
    ["Fizyoterapi ve Rehabilitasyon"],
    ["Çocuk Gelişimi"],
    ["Beslenme ve Diyetetik"],
    ["Ergoterapi"],
    ["Hukuk Fakültesi"],
    ["Odyoloji"],
    ["Geomatik Mühendisliği (İngilizce)"],
    ["Dil ve Konuşma Terapisi"],
    ["Çevre Mühendisliği (İngilizce)"],
    ["İnşaat Mühendisliği (İngilizce)"],
    ["Çağdaş Türk Lehçeleri ve Edebiyatları"],
    ["Ergoterapi (KKTC Uyruklu)"],
    ["Bilgisayar Mühendisliği (İngilizce)"],
    ["Türkçe Öğretmenliği"],
    ["Sosyal Hizmet"],
    ["Nükleer Enerji Mühendisliği (İngilizce) (KKTC Uyruklu)"],
    ["Özel Eğitim Öğretmenliği"],
    ["Sağlık Yönetimi"],
    ["Odyometri"],
    ["Tıbbi Dokümantasyon ve Sekreterlik"],
    ["Turizm ve Otel İşletmeciliği"],
    ["Muhasebe ve Vergi Uygulamaları"],
    ["Diş Protez Teknolojisi"],
    ["Tıbbi Laboratuvar Teknikleri"],
    ["Ortopedik Protez ve Ortez"],
    ["Tıbbi Görüntüleme Teknikleri"],
    ["Radyoterapi"],
    ["Eczane Hizmetleri"],
    ["Büro Yönetimi ve Yönetici Asistanlığı"],
    ["İlk ve Acil Yardım"],
    ["Alternatif Enerji Kaynakları Teknolojisi"],
    ["Endüstri Ürünleri Tasarımı"],
    ["Makine"],
    ["Ağız ve Diş Sağlığı"],
    ["Elektronörofizyoloji"],
    ["Elektrik"],
    ["Ameliyathane Hizmetleri"],
    ["Odyometri (KKTC Uyruklu)"],
    ["Bilgisayar Programcılığı"],
    ["Harita ve Kadastro"],
    ["İklimlendirme ve Soğutma Teknolojisi"],
    ["İnşaat Teknolojisi"],
    ["Odyoloji (KKTC Uyruklu)"],
    ["Tıp (İngilizce) (KKTC Uyruklu)"],
    ["Antropoloji"],
    ["İletişim Bilimleri"],
    ["Makine"],
    ["Makine Mühendisliği (İngilizce)"],
    ["Yapay Zeka Mühendisliği (İngilizce)"],
    ["Dezenfeksiyon"],
    ["Sahne Işık ve Ses Teknolojileri"],
    ["Almanca Mütercim ve Tercümanlık"],
    ["Fransızca Mütercim ve Tercümanlık"],
    ["İngilizce Mütercim ve Tercümanlık"],
    ["Kaynak Teknolojisi"],
    ["Alman Dili ve Edebiyatı (KKTC Uyruklu)"],
    ["Fizik (İngilizce) (Burslu)"],
    ["Kimya (İngilizce) (Burslu)"],
    ["Matematik (İngilizce) (Burslu)"],
    ["Moleküler Biyoloji ve Genetik (İngilizce) (Ücretli)"],
    ["Moleküler Biyoloji ve Genetik (İngilizce) (Burslu)"],
    ["İç Mimarlık ve Çevre Tasarımı (İngilizce) (Ücretli)"],
    ["İktisat (İngilizce) (Ücretli)"],
    ["İktisat (İngilizce) (Burslu)"],
    ["Psikoloji (İngilizce) (Ücretli)"],
    ["Psikoloji (İngilizce) (Burslu)"],
    ["Siyaset Bilimi ve Kamu Yönetimi (İngilizce) (Burslu)"],
    ["Uluslararası İlişkiler (İngilizce) (Ücretli)"],
    ["Uluslararası İlişkiler (İngilizce) (Burslu)"],
    ["İşletme (İngilizce) (Ücretli)"],
    ["İşletme (İngilizce) (Burslu)"],
    ["Bilgisayar Mühendisliği (İngilizce) (Ücretli)"],
    ["Bilgisayar Mühendisliği (İngilizce) (Burslu)"],
    ["Elektrik-Elektronik Mühendisliği (İngilizce) (Ücretli)"],
    ["Elektrik-Elektronik Mühendisliği (İngilizce) (Burslu)"],
    ["Endüstri Mühendisliği (İngilizce) (Ücretli)"],
    ["Endüstri Mühendisliği (İngilizce) (Burslu)"],
    ["Fizik (İngilizce) (%50 İndirimli)"],
    ["Kimya (İngilizce) (%50 İndirimli)"],
    ["Matematik (İngilizce) (%50 İndirimli)"],
    ["Moleküler Biyoloji ve Genetik (İngilizce) (%50 İndirimli)"],
    ["İç Mimarlık ve Çevre Tasarımı (İngilizce) (%50 İndirimli)"],
    ["Kentsel Tasarım ve Peyzaj Mimarlığı (İngilizce) (%50 İndirimli)"],
    ["İktisat (İngilizce) (%50 İndirimli)"],
    ["Psikoloji (İngilizce) (%50 İndirimli)"],
    ["Siyaset Bilimi ve Kamu Yönetimi (İngilizce) (%50 İndirimli)"],
    ["Uluslararası İlişkiler (İngilizce) (%50 İndirimli)"],
    ["Amerikan Kültürü ve Edebiyatı (İngilizce) (%50 İndirimli)"],
    ["İngiliz Dili ve Edebiyatı (İngilizce) (%50 İndirimli)"],
    ["İşletme (İngilizce) (%50 İndirimli)"],
    ["Bilgisayar Mühendisliği (İngilizce) (%50 İndirimli)"],
    ["Elektrik-Elektronik Mühendisliği (İngilizce) (%50 İndirimli)"],
    ["Endüstri Mühendisliği (İngilizce) (%50 İndirimli)"],
    ["Arkeoloji (İngilizce) (%50 İndirimli)"],
    ["Makine Mühendisliği (İngilizce) (Ücretli)"],
    ["Makine Mühendisliği (İngilizce) (Burslu)"],
    ["Makine Mühendisliği (İngilizce) (%50 İndirimli)"],
    ["Amerikan Kültürü ve Edebiyatı (İngilizce) (Burslu)"],
    ["Arkeoloji (İngilizce) (Burslu)"],
    ["Felsefe (İngilizce) (Burslu)"],
    ["İngiliz Dili ve Edebiyatı (İngilizce) (Burslu)"],
    ["İç Mimarlık ve Çevre Tasarımı (İngilizce) (Burslu)"],
    ["Kentsel Tasarım ve Peyzaj Mimarlığı (İngilizce) (Burslu)"],
    ["Mimarlık (İngilizce) (Ücretli)"],
    ["Mimarlık (İngilizce) (Burslu)"],
    ["Mimarlık (İngilizce) (%50 İndirimli)"],
    ["Siyaset Bilimi ve Kamu Yönetimi (İngilizce) (Ücretli)"],
    ["Hukuk Fakültesi (Burslu)"],
    ["Hukuk Fakültesi (%50 İndirimli)"],
    ["Hukuk Fakültesi (Ücretli)"],
    ["İngilizce"],
    ["İngilizce"],
    ["Grafik Tasarımı (İngilizce) (Ücretli)"],
    ["Grafik Tasarımı (İngilizce) (Burslu)"],
    ["Grafik Tasarımı (İngilizce) (%50 İndirimli)"],
    ["İletişim ve Tasarımı (İngilizce) (Ücretli)"],
    ["İletişim ve Tasarımı (İngilizce) (Burslu)"],
    ["İletişim ve Tasarımı (İngilizce) (%50 İndirimli)"],
    ["Fizik (İngilizce) (Ücretli)"],
    ["Kimya (İngilizce) (Ücretli)"],
    ["Matematik (İngilizce) (Ücretli)"],
    ["Bilişim Sistemleri ve Teknolojileri (İngilizce) (Ücretli)"],
    ["Bilişim Sistemleri ve Teknolojileri (İngilizce) (Burslu)"],
    ["Bilişim Sistemleri ve Teknolojileri (İngilizce) (%50 İndirimli)"],
    ["Turizm ve Otel İşletmeciliği (İngilizce) (Burslu)"],
    ["Turizm ve Otel İşletmeciliği (İngilizce) (%50 İndirimli)"],
    ["Tıp Fakültesi (Burslu)"],
    ["Ebelik (Burslu)"],
    ["Beslenme ve Diyetetik (Burslu)"],
    ["Beslenme ve Diyetetik (%25 İndirimli)"],
    ["Fizyoterapi ve Rehabilitasyon (Burslu)"],
    ["Fizyoterapi ve Rehabilitasyon (%25 İndirimli)"],
    ["Eczacılık Fakültesi (Burslu)"],
    ["Eczacılık Fakültesi (%25 İndirimli)"],
    ["Anestezi (Burslu)"],
    ["Anestezi (%25 İndirimli)"],
    ["İlk ve Acil Yardım (Burslu)"],
    ["İlk ve Acil Yardım (%25 İndirimli)"],
    ["Diş Hekimliği Fakültesi (Burslu)"],
    ["Ağız ve Diş Sağlığı (Burslu)"],
    ["Ağız ve Diş Sağlığı (%25 İndirimli)"],
    ["Ameliyathane Hizmetleri (Burslu)"],
    ["Ameliyathane Hizmetleri (%25 İndirimli)"],
    ["Diş Protez Teknolojisi (Burslu)"],
    ["Diş Protez Teknolojisi (%25 İndirimli)"],
    ["Eczane Hizmetleri (Burslu)"],
    ["Tıbbi Görüntüleme Teknikleri (Burslu)"],
    ["Tıbbi Görüntüleme Teknikleri (%25 İndirimli)"],
    ["Tıbbi Laboratuvar Teknikleri (Burslu)"],
    ["Tıbbi Laboratuvar Teknikleri (%25 İndirimli)"],
    ["Ebelik (%50 İndirimli)"],
    ["Hemşirelik (Burslu)"],
    ["Hemşirelik (%50 İndirimli)"],
    ["Spor Yöneticiliği (Burslu)"],
    ["Spor Yöneticiliği (%50 İndirimli)"],
    ["Rekreasyon (Burslu)"],
    ["Rekreasyon (%50 İndirimli)"],
    ["Yaşlı Bakımı (Burslu)"],
    ["Diyaliz (Burslu)"],
    ["Diyaliz (%25 İndirimli)"],
    ["Eczane Hizmetleri (%50 İndirimli)"],
    ["Diş Hekimliği Fakültesi (%25 İndirimli)"],
    ["Tıp Fakültesi (%25 İndirimli)"],
    ["Eczacılık Fakültesi (İngilizce) (Burslu)"],
    ["Eczacılık Fakültesi (İngilizce) (%25 İndirimli)"],
    ["Dil ve Konuşma Terapisi (Burslu)"],
    ["Dil ve Konuşma Terapisi (%50 İndirimli)"],
    ["Ergoterapi (Burslu)"],
    ["Ergoterapi (%50 İndirimli)"],
    ["Odyoloji (Burslu)"],
    ["Odyoloji (%50 İndirimli)"],
    ["Tıp Fakültesi (İngilizce) (Burslu)"],
    ["Tıp Fakültesi (İngilizce) (%25 İndirimli)"],
    ["Optisyenlik (Burslu)"],
    ["Optisyenlik (%25 İndirimli)"],
    ["Bilgisayar ve Öğretim Teknolojileri Öğretmenliği (İngilizce)"],
    ["Fen Bilgisi Öğretmenliği (İngilizce)"],
    ["Fizik Öğretmenliği (İngilizce)"],
    ["İlköğretim Matematik Öğretmenliği (İngilizce)"],
    ["İngilizce Öğretmenliği (İngilizce)"],
    ["İngilizce Öğretmenliği (İngilizce) (UOLP-SUNY New Paltz) (Ücretli)"],
    ["İngilizce Öğretmenliği (İngilizce) (UOLP-SUNY New Paltz) (%50 İndirimli)"],
    ["Kimya Öğretmenliği (İngilizce)"],
    ["Okul Öncesi Öğretmenliği (İngilizce)"],
    ["Biyoloji (İngilizce)"],
    ["Felsefe (İngilizce)"],
    ["Fizik (İngilizce)"],
    ["İstatistik (İngilizce)"],
    ["Kimya (İngilizce)"],
    ["Matematik (İngilizce)"],
    ["Moleküler Biyoloji ve Genetik (İngilizce)"],
    ["Psikoloji (İngilizce)"],
    ["Sosyoloji (İngilizce)"],
    ["Tarih (İngilizce)"],
    ["İktisat (İngilizce)"],
    ["İşletme (İngilizce)"],
    ["İşletme (İngilizce) (UOLP-SUNY Binghamton) (Ücretli)"],
    ["İşletme (İngilizce) (UOLP-SUNY Binghamton) (%50 İndirimli)"],
    ["Küresel Siyaset ve Uluslararası İlişkiler (İngilizce) (UOLP-SUNY Binghamton) (Ücretli)"],
    ["Küresel Siyaset ve Uluslararası İlişkiler (İngilizce) (UOLP-SUNY Binghamton) (%50 İndirimli)"],
    ["Siyaset Bilimi ve Kamu Yönetimi (İngilizce)"],
    ["Uluslararası İlişkiler (İngilizce)"],
    ["Mimarlık (İngilizce)"],
    ["Şehir ve Bölge Planlama (İngilizce)"],
    ["Bilgisayar Mühendisliği (İngilizce)"],
    ["Çevre Mühendisliği (İngilizce)"],
    ["Elektrik-Elektronik Mühendisliği (İngilizce)"],
    ["Endüstri Mühendisliği (İngilizce)"],
    ["Gıda Mühendisliği (İngilizce)"],
    ["Havacılık ve Uzay Mühendisliği (İngilizce)"],
    ["İnşaat Mühendisliği (İngilizce)"],
    ["Jeoloji Mühendisliği (İngilizce)"],
    ["Kimya Mühendisliği (İngilizce)"],
    ["Maden Mühendisliği (İngilizce)"],
    ["Makine Mühendisliği (İngilizce)"],
    ["Metalurji ve Malzeme Mühendisliği (İngilizce)"],
    ["Petrol ve Doğalgaz Mühendisliği (İngilizce)"],
    ["Matematik Öğretmenliği (İngilizce)"],
    ["Felsefe (İngilizce) (KKTC Uyruklu)"],
    ["Endüstriyel Tasarım (İngilizce)"],
    ["Gıda Mühendisliği (İngilizce) (KKTC Uyruklu)"],
    ["Lojistik (Burslu)"],
    ["Elektronik Teknolojisi (Burslu)"],
    ["Elektronik Teknolojisi (%50 İndirimli)"],
    ["Makine (Burslu)"],
    ["Makine (%50 İndirimli)"],
    ["Mekatronik (Burslu)"],
    ["Mekatronik (%50 İndirimli)"],
    ["Bilgisayar Mühendisliği (İngilizce) (Burslu)"],
    ["Bilgisayar Mühendisliği (İngilizce) (%50 İndirimli)"],
    ["Elektrik-Elektronik Mühendisliği (İngilizce) (Burslu)"],
    ["Makine Mühendisliği (İngilizce) (Burslu)"],
    ["Bilişim Güvenliği Teknolojisi (Burslu)"],
    ["Bilişim Güvenliği Teknolojisi (%50 İndirimli)"],
    ["E-Ticaret ve Pazarlama (Burslu)"],
    ["E-Ticaret ve Pazarlama (%50 İndirimli)"],
    ["Bilgisayar Programcılığı (Burslu)"],
    ["Bilgisayar Programcılığı (%50 İndirimli)"],
    ["Uluslararası Ticaret ve Finansman (İngilizce) (Burslu)"],
    ["Yazılım Mühendisliği (Burslu)"],
    ["Yazılım Mühendisliği (%50 İndirimli)"],
    ["Ekonomi (İngilizce) (Burslu)"],
    ["Ekonomi (İngilizce) (%50 İndirimli)"],
    ["Yönetim Bilişim Sistemleri (Burslu)"],
    ["Yönetim Bilişim Sistemleri (%50 İndirimli)"],
    ["Biyomedikal Cihaz Teknolojisi (Burslu)"],
    ["Biyomedikal Cihaz Teknolojisi (%50 İndirimli)"],
    ["Elektrik (Burslu)"],
    ["Elektrik (%50 İndirimli)"],
    ["Hibrid ve Elektrikli Taşıtlar Teknolojisi (Burslu)"],
    ["Hibrid ve Elektrikli Taşıtlar Teknolojisi (%50 İndirimli)"],
    ["İnsansız Hava Aracı Teknolojisi ve Operatörlüğü (Burslu)"],
    ["İnsansız Hava Aracı Teknolojisi ve Operatörlüğü (%50 İndirimli)"],
    ["Endüstriyel Tasarım (Burslu)"],
    ["Endüstriyel Tasarım (%50 İndirimli)"],
    ["İç Mimarlık ve Çevre Tasarımı (Burslu)"],
    ["İç Mimarlık ve Çevre Tasarımı (%50 İndirimli)"],
    ["Endüstri Mühendisliği (Burslu)"],
    ["Endüstri Mühendisliği (%50 İndirimli)"],
    ["İşletme (İngilizce) (Burslu)"],
    ["İşletme (İngilizce) (%50 İndirimli)"],
    ["Pazarlama (İngilizce) (Burslu)"],
    ["Pazarlama (İngilizce) (%50 İndirimli)"],
    ["Yönetim Bilişim Sistemleri (İngilizce) (Burslu)"],
    ["Yönetim Bilişim Sistemleri (İngilizce) (%50 İndirimli)"],
    ["Bilgisayar Mühendisliği (Burslu)"],
    ["Bilgisayar Mühendisliği (%50 İndirimli)"],
    ["Elektrik-Elektronik Mühendisliği (İngilizce) (%50 İndirimli)"],
    ["Malzeme Bilimi ve Mühendisliği (İngilizce) (Burslu)"],
    ["Malzeme Bilimi ve Mühendisliği (İngilizce) (%50 İndirimli)"],
    ["Yazılım Mühendisliği (İngilizce) (Burslu)"],
    ["Yazılım Mühendisliği (İngilizce) (%50 İndirimli)"],
    ["Silah Sanayi Teknikerliği (Burslu)"],
    ["Silah Sanayi Teknikerliği (%50 İndirimli)"],
    ["Lojistik (%50 İndirimli)"],
    ["Gülhane Diş Hekimliği Fakültesi (Ankara)"],
    ["Gülhane Tıp (Ankara)"],
    ["Gülhane Tıp (Ankara) (Erkek) (Milli Savunma Bakanlığı Adına)"],
    ["Gülhane Tıp (Ankara) (Kız) (Milli Savunma Bakanlığı Adına)"],
    ["Gülhane Tıp (Ankara) (Erkek) (İçişleri Bakanlığı Adına)"],
    ["Ameliyathane Hizmetleri (Ankara)"],
    ["Anestezi (Ankara)"],
    ["Eczane Hizmetleri (Ankara)"],
    ["Elektronörofizyoloji (Ankara)"],
    ["Sağlık Kurumları İşletmeciliği (Ankara)"],
    ["Ortopedik Protez ve Ortez (Ankara)"],
    ["Patoloji Laboratuvar Teknikleri (Ankara)"],
    ["Tıbbi Görüntüleme Teknikleri (Ankara)"],
    ["Tıbbi Laboratuvar Teknikleri (Ankara)"],
    ["Yaşlı Bakımı (Ankara)"],
    ["İlk ve Acil Yardım (Ankara)"],
    ["Diş Protez Teknolojisi (Ankara)"],
    ["İlk ve Acil Yardım (Erkek) (Ankara) (İçişleri Bakanlığı Adına)"],
    ["İlk ve Acil Yardım (Erkek) (Ankara) (Milli Savunma Bakanlığı Adına)"],
    ["Hemşirelik (Ankara)"],
    ["Gülhane Eczacılık Fakültesi (Ankara)"],
    ["Beslenme ve Diyetetik (Ankara)"],
    ["Çocuk Gelişimi (Ankara)"],
    ["Ebelik (Ankara)"],
    ["Ergoterapi (Ankara)"],
    ["Odyoloji (Ankara)"],
    ["Sağlık Yönetimi (Ankara)"],
    ["Sosyal Hizmet (Ankara)"],
    ["Gülhane Diş Hekimliği Fakültesi (Ankara) (Erkek) (İçişleri Bakanlığı Adına)"],
    ["Gülhane Diş Hekimliği Fakültesi (Ankara) (Erkek) (Milli Savunma Bakanlığı Adına)"],
    ["Gülhane Eczacılık Fakültesi (Ankara) (Erkek) (Milli Savunma Bakanlığı Adına)"],
    ["Ameliyathane Hizmetleri (Ankara) (Erkek) (Milli Savunma Bakanlığı Adına)"],
    ["Anestezi (Ankara) (Erkek) (Milli Savunma Bakanlığı Adına)"],
    ["Tıbbi Görüntüleme Teknikleri (Ankara) (Erkek) (Milli Savunma Bakanlığı Adına)"],
    ["Tıbbi Laboratuvar Teknikleri (Ankara) (Erkek) (Milli Savunma Bakanlığı Adına)"],
    ["Ağız ve Diş Sağlığı (Ankara)"],
    ["Ortez ve Protez (Ankara)"],
    ["Eczane Hizmetleri (Ankara) (Erkek) (Milli Savunma Bakanlığı Adına)"],
    ["Gülhane Diş Hekimliği Fakültesi (Ankara) (Kız) (İçişleri Bakanlığı Adına)"],
    ["Gülhane Tıp (Ankara) (Kız) (İçişleri Bakanlığı Adına)"],
    ["İlk ve Acil Yardım (Ankara) (Kız) (İçişleri Bakanlığı Adına)"],
    ["Fizyoterapi ve Rehabilitasyon (Ankara)"],
    ["İktisadi ve İdari Bilimler Programları (İngilizce) (Burslu)"],
    ["Mühendislik Programları (İngilizce) (Burslu)"],
    ["İktisadi ve İdari Bilimler Programları (İngilizce) (%50 İndirimli)"],
    ["Mühendislik Programları (İngilizce) (%50 İndirimli)"],
    ["Psikoloji (İngilizce) (Ücretli)"],
    ["Psikoloji (İngilizce) (Burslu)"],
    ["Psikoloji (İngilizce) (%50 İndirimli)"],
    ["Mühendislik Programları (İngilizce) (Ücretli)"],
    ["İngilizce Öğretmenliği (İngilizce) (Burslu)"],
    ["İngilizce Öğretmenliği (İngilizce) (%50 İndirimli)"],
    ["Sınıf Öğretmenliği (İngilizce) (Burslu)"],
    ["Sınıf Öğretmenliği (İngilizce) (%50 İndirimli)"],
    ["İlköğretim Matematik Öğretmenliği (İngilizce) (Burslu)"],
    ["İlköğretim Matematik Öğretmenliği (İngilizce) (%50 İndirimli)"],
    ["Sosyoloji (İngilizce) (Burslu)"],
    ["Sosyoloji (İngilizce) (%50 İndirimli)"],
    ["Okul Öncesi Öğretmenliği (İngilizce) (Burslu)"],
    ["Okul Öncesi Öğretmenliği (İngilizce) (%50 İndirimli)"],
    ["Rehberlik ve Psikolojik Danışmanlık (İngilizce) (Burslu)"],
    ["Rehberlik ve Psikolojik Danışmanlık (İngilizce) (%50 İndirimli)"],
    ["Matematik (İngilizce) (Burslu)"],
    ["İngiliz Dili ve Edebiyatı (İngilizce) (Burslu)"],
    ["İngiliz Dili ve Edebiyatı (İngilizce) (%50 İndirimli)"],
    ["Matematik (İngilizce) (%50 İndirimli)"],
    ["Yazılım Mühendisliği (İngilizce) (Burslu)"],
    ["Yazılım Mühendisliği (İngilizce) (%50 İndirimli)"],
    ["Görsel İletişim Tasarımı (İngilizce) (Burslu)"],
    ["Görsel İletişim Tasarımı (İngilizce) (%50 İndirimli)"],
    ["Yazılım Mühendisliği (İngilizce) (Ücretli)"],
    ["Endüstriyel Tasarım (İngilizce) (Burslu)"],
    ["Endüstriyel Tasarım (İngilizce) (%50 İndirimli)"],
    ["İç Mimarlık ve Çevre Tasarımı (İngilizce) (Ücretli)"],
    ["İç Mimarlık ve Çevre Tasarımı (İngilizce) (%50 İndirimli)"],
    ["İç Mimarlık ve Çevre Tasarımı (İngilizce) (Burslu)"],
    ["Şehir ve Bölge Planlama (İngilizce) (Burslu)"],
    ["Şehir ve Bölge Planlama (İngilizce) (%50 İndirimli)"],
    ["Mimarlık (İngilizce) (Ücretli)"],
    ["Mimarlık (İngilizce) (Burslu)"],
    ["Mimarlık (İngilizce) (%50 İndirimli)"],
    ["Tarih (Burslu)"],
    ["Türk Dili ve Edebiyatı (Burslu)"],
    ["İktisat (Ücretli)"],
    ["İktisat (Burslu)"],
    ["İşletme (Ücretli)"],
    ["İşletme (Burslu)"],
    ["Bilgisayar Mühendisliği (Ücretli)"],
    ["Bilgisayar Mühendisliği (Burslu)"],
    ["Elektrik-Elektronik Mühendisliği (Ücretli)"],
    ["Elektrik-Elektronik Mühendisliği (Burslu)"],
    ["Endüstri Mühendisliği (Ücretli)"],
    ["Endüstri Mühendisliği (Burslu)"],
    ["Makine Mühendisliği (Ücretli)"],
    ["Makine Mühendisliği (Burslu)"],
    ["Hukuk Fakültesi (Ücretli)"],
    ["Hukuk Fakültesi (Burslu)"],
    ["İktisat (%50 İndirimli)"],
    ["İşletme (%50 İndirimli)"],
    ["Bilgisayar Mühendisliği (%50 İndirimli)"],
    ["Elektrik-Elektronik Mühendisliği (%50 İndirimli)"],
    ["Endüstri Mühendisliği (%50 İndirimli)"],
    ["Makine Mühendisliği (%50 İndirimli)"],
    ["Hukuk Fakültesi (%50 İndirimli)"],
    ["Uluslararası Girişimcilik (Ücretli)"],
    ["Uluslararası Girişimcilik (Burslu)"],
    ["Uluslararası Girişimcilik (%50 İndirimli)"],
    ["Biyomedikal Mühendisliği (Ücretli)"],
    ["Biyomedikal Mühendisliği (Burslu)"],
    ["Biyomedikal Mühendisliği (%50 İndirimli)"],
    ["Mimarlık (Burslu)"],
    ["Mimarlık (%50 İndirimli)"],
    ["Tarih (%50 İndirimli)"],
    ["Türk Dili ve Edebiyatı (%50 İndirimli)"],
    ["İngiliz Dili ve Edebiyatı (İngilizce) (Burslu)"],
    ["İngiliz Dili ve Edebiyatı (İngilizce) (%50 İndirimli)"],
    ["Mimarlık (Ücretli)"],
    ["Malzeme Bilimi ve Nanoteknoloji Mühendisliği (Ücretli)"],
    ["Malzeme Bilimi ve Nanoteknoloji Mühendisliği (Burslu)"],
    ["Malzeme Bilimi ve Nanoteknoloji Mühendisliği (%50 İndirimli)"],
    ["İç Mimarlık ve Çevre Tasarımı (Ücretli)"],
    ["İç Mimarlık ve Çevre Tasarımı (Burslu)"],
    ["İç Mimarlık ve Çevre Tasarımı (%50 İndirimli)"],
    ["Görsel İletişim Tasarımı (Burslu)"],
    ["Görsel İletişim Tasarımı (%50 İndirimli)"],
    ["Görsel İletişim Tasarımı (Ücretli)"],
    ["Psikoloji (Ücretli)"],
    ["Psikoloji (Burslu)"],
    ["Psikoloji (%50 İndirimli)"],
    ["Tıp Fakültesi (Burslu)"],
    ["Tıp Fakültesi (%50 İndirimli)"],
    ["Tıp Fakültesi (Ücretli)"],
    ["Endüstriyel Tasarım (Burslu)"],
    ["Endüstriyel Tasarım (%50 İndirimli)"],
    ["Siyaset Bilimi ve Uluslararası İlişkiler (Ücretli)"],
    ["Siyaset Bilimi ve Uluslararası İlişkiler (Burslu)"],
    ["Siyaset Bilimi ve Uluslararası İlişkiler (%50 İndirimli)"],
    ["Yapay Zeka Mühendisliği (İngilizce) (Burslu)"],
    ["İngiliz Dili ve Edebiyatı (İngilizce) (Ücretli)"],
    ["Endüstriyel Tasarım (Ücretli)"],
    ["Yapay Zeka Mühendisliği (İngilizce) (Ücretli)"],
    ["Yapay Zeka Mühendisliği (İngilizce) (%50 İndirimli)"],
    ["İşletme (İngilizce) (Burslu)"],
    ["İşletme (İngilizce) (%50 İndirimli)"],
    ["Pilotaj (İngilizce) (Ücretli)"],
    ["Pilotaj (İngilizce) (Burslu)"],
    ["Uçak Mühendisliği (İngilizce) (Burslu)"],
    ["Uzay Mühendisliği (İngilizce) (Burslu)"],
    ["Uzay Mühendisliği (İngilizce) (%50 İndirimli)"],
    ["Lojistik Yönetimi (İngilizce) (Burslu)"],
    ["Lojistik Yönetimi (İngilizce) (%50 İndirimli)"],
    ["Bilgisayar Mühendisliği (İngilizce) (Burslu)"],
    ["Bilgisayar Mühendisliği (İngilizce) (%50 İndirimli)"],
    ["Elektrik-Elektronik Mühendisliği (İngilizce) (Burslu)"],
    ["Elektrik-Elektronik Mühendisliği (İngilizce) (%50 İndirimli)"],
    ["Makine Mühendisliği (İngilizce) (Burslu)"],
    ["Makine Mühendisliği (İngilizce) (%50 İndirimli)"],
    ["Endüstri Mühendisliği (İngilizce) (Burslu)"],
    ["Endüstri Mühendisliği (İngilizce) (%50 İndirimli)"],
    ["Bilgisayar Mühendisliği (İngilizce) (Ücretli)"],
    ["Havacılık Yönetimi (İngilizce) (Burslu)"],
    ["Havacılık Yönetimi (İngilizce) (%50 İndirimli)"],
    ["Sivil Havacılık Kabin Hizmetleri (Ücretli)"],
    ["Sivil Havacılık Kabin Hizmetleri (Burslu)"],
    ["Uçak Teknolojisi (Ücretli)"],
    ["Uçak Teknolojisi (Burslu)"],
    ["Sivil Havacılık Kabin Hizmetleri (Ücretli)"],
    ["Sivil Havacılık Kabin Hizmetleri (Burslu)"],
    ["Uçak Teknolojisi (Ücretli)"],
    ["Uçak Teknolojisi (Burslu)"],
    ["Sivil Hava Ulaştırma İşletmeciliği (Ücretli)"],
    ["Sivil Hava Ulaştırma İşletmeciliği (Burslu)"],
    ["Uçak Mühendisliği (İngilizce) (Ücretli)"],
    ["Havacılık Yönetimi (İngilizce) (Ücretli)"],
    ["Hava Lojistiği (Burslu)"],
    ["Hava Lojistiği (Burslu)"],
    ["Sivil Hava Ulaştırma İşletmeciliği (Ücretli)"],
    ["Sivil Hava Ulaştırma İşletmeciliği (Burslu)"],
    ["Yönetim Bilişim Sistemleri (İngilizce) (Burslu)"],
    ["Yönetim Bilişim Sistemleri (İngilizce) (%50 İndirimli)"],
    ["Yönetim Bilişim Sistemleri (Burslu)"],
    ["Yönetim Bilişim Sistemleri (%50 İndirimli)"],
    ["Uzay Mühendisliği (İngilizce) (Ücretli)"],
    ["Yazılım Mühendisliği (İngilizce) (Burslu)"],
    ["Yazılım Mühendisliği (İngilizce) (Ücretli)"],
    ["Hava Lojistiği (%50 İndirimli)"],
    ["Hava Lojistiği (%50 İndirimli)"],
    ["Sivil Hava Ulaştırma İşletmeciliği (%50 İndirimli)"],
    ["Yazılım Mühendisliği (İngilizce) (%50 İndirimli)"],
    ["Sivil Hava Ulaştırma İşletmeciliği (%50 İndirimli)"],
    ["İngilizce Öğretmenliği (Burslu)"],
    ["Psikoloji (Ücretli)"],
    ["Psikoloji (Burslu)"],
    ["Hukuk Fakültesi (Ücretli)"],
    ["Hukuk Fakültesi (Burslu)"],
    ["İşletme (Burslu)"],
    ["Siyaset Bilimi ve Uluslararası İlişkiler (Burslu)"],
    ["Tıp Fakültesi (Ücretli)"],
    ["Tıp Fakültesi (Burslu)"],
    ["Hemşirelik Yüksekokulu (Ücretli)"],
    ["Hemşirelik Yüksekokulu (Burslu)"],
    ["Rehberlik ve Psikolojik Danışmanlık (Burslu)"],
    ["İşletme (%50 İndirimli)"],
    ["İngilizce Öğretmenliği (%25 İndirimli)"],
    ["Siyaset Bilimi ve Uluslararası İlişkiler (%50 İndirimli)"],
    ["Yönetim Bilişim Sistemleri (Burslu)"],
    ["Yönetim Bilişim Sistemleri (%50 İndirimli)"],
    ["Anestezi (Ücretli)"],
    ["Anestezi (Burslu)"],
    ["Fizyoterapi (Ücretli)"],
    ["Fizyoterapi (Burslu)"],
    ["Tıbbi Laboratuvar Teknikleri (Ücretli)"],
    ["Tıbbi Laboratuvar Teknikleri (Burslu)"],
    ["İlk ve Acil Yardım (Ücretli)"],
    ["İlk ve Acil Yardım (Burslu)"],
    ["Tıbbi Görüntüleme Teknikleri (Ücretli)"],
    ["Tıbbi Görüntüleme Teknikleri (Burslu)"],
    ["Adalet (Ücretli)"],
    ["Adalet (Burslu)"],
    ["Ameliyathane Hizmetleri (Ücretli)"],
    ["Ameliyathane Hizmetleri (Burslu)"],
    ["Elektronörofizyoloji (Ücretli)"],
    ["Elektronörofizyoloji (Burslu)"],
    ["Bilgisayar Programcılığı (Burslu)"],
    ["Bilgisayar Programcılığı (%50 İndirimli)"],
    ["İşletme Yönetimi (Burslu)"],
    ["İşletme Yönetimi (%50 İndirimli)"],
    ["Muhasebe ve Vergi Uygulamaları (Burslu)"],
    ["Muhasebe ve Vergi Uygulamaları (%50 İndirimli)"],
    ["Patoloji Laboratuvar Teknikleri (Ücretli)"],
    ["Patoloji Laboratuvar Teknikleri (Burslu)"],
    ["Bilgisayar Teknolojisi (Burslu)"],
    ["Bilgisayar Teknolojisi (%50 İndirimli)"],
    ["Sağlık Kurumları İşletmeciliği (Burslu)"],
    ["Sağlık Kurumları İşletmeciliği (%50 İndirimli)"],
    ["Rehberlik ve Psikolojik Danışmanlık (%50 İndirimli)"],
    ["Psikoloji (%50 İndirimli)"],
    ["Adalet (%50 İndirimli)"],
    ["Ameliyathane Hizmetleri (%50 İndirimli)"],
    ["Elektronörofizyoloji (%50 İndirimli)"],
    ["Patoloji Laboratuvar Teknikleri (%50 İndirimli)"],
    ["Tıbbi Laboratuvar Teknikleri (%50 İndirimli)"],
    ["Hemşirelik Yüksekokulu (%50 İndirimli)"],
    ["Bilişim Güvenliği Teknolojisi (Burslu)"],
    ["Bilişim Güvenliği Teknolojisi (%50 İndirimli)"],
    ["Uygulamalı İngilizce Çevirmenlik (İngilizce) (Burslu)"],
    ["Uygulamalı İngilizce Çevirmenlik (İngilizce) (%50 İndirimli)"],
    ["Uluslararası Ticaret ve Finansman (Burslu)"],
    ["Uluslararası Ticaret ve Finansman (%50 İndirimli)"],
    ["Hukuk Fakültesi (%50 İndirimli)"],
    ["Tıp Fakültesi (Burslu)"],
    ["Tıp Fakültesi (Ücretli)"],
    ["Beslenme ve Diyetetik (Burslu)"],
    ["Beslenme ve Diyetetik (Ücretli)"],
    ["Fizyoterapi ve Rehabilitasyon (Ücretli)"],
    ["Fizyoterapi ve Rehabilitasyon (Burslu)"],
    ["Sağlık Yönetimi (Ücretli)"],
    ["Sağlık Yönetimi (Burslu)"],
    ["Hemşirelik (Burslu)"],
    ["Hemşirelik (Ücretli)"],
    ["Tıbbi Dokümantasyon ve Sekreterlik (Burslu)"],
    ["Tıbbi Dokümantasyon ve Sekreterlik (Ücretli)"],
    ["Ameliyathane Hizmetleri (Ücretli)"],
    ["Ameliyathane Hizmetleri (Burslu)"],
    ["Elektronörofizyoloji (Burslu)"],
    ["Elektronörofizyoloji (Ücretli)"],
    ["Anestezi (Burslu)"],
    ["Anestezi (%25 İndirimli)"],
    ["Anestezi (Ücretli)"],
    ["Fizyoterapi ve Rehabilitasyon (%50 İndirimli)"],
    ["Sağlık Yönetimi (%50 İndirimli)"],
    ["Ameliyathane Hizmetleri (%25 İndirimli)"],
    ["Tıbbi Dokümantasyon ve Sekreterlik (%50 İndirimli)"],
    ["Beslenme ve Diyetetik (%50 İndirimli)"],
    ["Hemşirelik (%50 İndirimli)"],
    ["Elektronörofizyoloji (%25 İndirimli)"],
    ["Tıbbi Tanıtım ve Pazarlama (Burslu)"],
    ["Tıbbi Tanıtım ve Pazarlama (%50 İndirimli)"],
    ["Tıbbi Laboratuvar Teknikleri (Burslu)"],
    ["Tıbbi Laboratuvar Teknikleri (%25 İndirimli)"],
    ["Biyomedikal Cihaz Teknolojisi (Burslu)"],
    ["Biyomedikal Cihaz Teknolojisi (%50 İndirimli)"],
    ["Optisyenlik (Burslu)"],
    ["Optisyenlik (%25 İndirimli)"],
    ["Eczane Hizmetleri (Burslu)"],
    ["Eczane Hizmetleri (%25 İndirimli)"],
    ["Bilgisayar Programcılığı (Burslu)"],
    ["Bilgisayar Programcılığı (%25 İndirimli)"],
    ["Bilgisayar Programcılığı (Ücretli)"],
    ["Biyomedikal Cihaz Teknolojisi (Ücretli)"],
    ["Optisyenlik (Ücretli)"],
    ["Tıbbi Laboratuvar Teknikleri (Ücretli)"],
    ["Eczane Hizmetleri (Ücretli)"],
    ["Dil ve Konuşma Terapisi (Ücretli)"],
    ["Dil ve Konuşma Terapisi (Burslu)"],
    ["Tıp Fakültesi (%50 İndirimli)"],
    ["Tıp Fakültesi (İngilizce) (Ücretli)"],
    ["Tıp Fakültesi (İngilizce) (Burslu)"],
    ["Tıbbi Tanıtım ve Pazarlama (Ücretli)"],
    ["Dil ve Konuşma Terapisi (%50 İndirimli)"],
    ["Tıp Fakültesi (İngilizce) (%50 İndirimli)"]
  ]

  
// programlar uniq hale getirildi

var program_sayisi= programlar.length

uniqprogramlar=[];
for (i=0; i<program_sayisi; i++) {  
    if (!uniqprogramlar.includes(programlar[i][0])) {
        uniqprogramlar.push(programlar[i][0]); 
    }
}

// programlar opsiyon olarak eklendi
var options = '';

var uni_program_sayisi=uniqprogramlar.length;


for (var i = 0; i < uni_program_sayisi; i++) {
    options += '<option value="' + uniqprogramlar[i] + '" />';
  }
  
  document.getElementById('bölümlerist').innerHTML = options;


  module.export= {programlar};